# Redirect domain aliases to primary domain
[[redirects]]
from = "https://www.imhoff.name/*"
to = "https://www.stefanimhoff.de/:splat"
status = 301
force = true

[[redirects]]
from = "https://stefan.imhoff.name/*"
to = "https://www.stefanimhoff.de/:splat"
status = 301
force = true

[[redirects]]
from = "https://imhoff.name/*"
to = "https://www.stefanimhoff.de/:splat"
status = 301
force = true

# Redirects
[[redirects]]
from = "/notiz/das-koi-design-inspiration-und-idee"
to = "/2007/koi-design"
status = 301
force = true

[[redirects]]
from = "/notiz/django-folder-fuer-mac-os-x"
to = "/2007/django-folder-mac-osx"
status = 301
force = true

[[redirects]]
from = "/notiz/django-folder-mac-osx"
to = "/2007/django-folder-mac-osx"
status = 301
force = true

[[redirects]]
from = "/notiz/blender-folder-fuer-mac-os-x-leopard"
to = "/2008/blender-folder-mac-osx"
status = 301
force = true

[[redirects]]
from = "/notiz/theme-kaijin-fuer-das-moinmoin-wiki"
to = "/2008/theme-kaijin-moinmoin-wiki"
status = 301
force = true

[[redirects]]
from = "/notiz/theme-kaijin-moinmoin-wiki"
to = "/2008/theme-kaijin-moinmoin-wiki"
status = 301
force = true

[[redirects]]
from = "/notiz/terminal-stoeckchen"
to = "/2008/terminal-most-used-commands"
status = 301
force = true

[[redirects]]
from = "/notiz/django-relaunch-von-kogakure-de"
to = "/2008/django-relaunch-kogakure-de"
status = 301
force = true

[[redirects]]
from = "/notiz/django-relaunch-kogakure-de"
to = "/2008/django-relaunch-kogakure-de"
status = 301
force = true

[[redirects]]
from = "/notiz/server-verwaltung-mit-capistrano"
to = "/2008/server-verwaltung-capistrano"
status = 301
force = true

[[redirects]]
from = "/notiz/server-verwaltung-capistrano"
to = "/2008/server-verwaltung-capistrano"
status = 301
force = true

[[redirects]]
from = "/notiz/grundlagen-von-python-django-fuer-anfaenger"
to = "/2008/grundlagen-python-django-anfaenger"
status = 301
force = true

[[redirects]]
from = "/notiz/grundlagen-python-django-anfaenger"
to = "/2008/grundlagen-python-django-anfaenger"
status = 301
force = true

[[redirects]]
from = "/notiz/kostenlose-vektorkarten-mit-openstreetmap"
to = "/2008/kostenlose-vektorkarten-openstreetmap"
status = 301
force = true

[[redirects]]
from = "/notiz/kostenlose-vektorkarten-openstreetmap"
to = "/2008/kostenlose-vektorkarten-openstreetmap"
status = 301
force = true

[[redirects]]
from = "/notiz/2008-django-git"
to = "/2008/django-git"
status = 301
force = true

[[redirects]]
from = "/notiz/django-fuer-webdesigner"
to = "/2009/django-webdesigner"
status = 301
force = true

[[redirects]]
from = "/notiz/django-webdesigner"
to = "/2009/django-webdesigner"
status = 301
force = true

[[redirects]]
from = "/notiz/2010-jahresrueckblick"
to = "/2010/jahresrueckblick"
status = 301
force = true

[[redirects]]
from = "/notiz/mein-setup-2013"
to = "/2013/mein-setup"
status = 301
force = true

[[redirects]]
from = "/notiz/volume-reparieren-unter-mac-osx"
to = "/2007/volume-reparieren-unter-mac-osx"
status = 301
force = true

[[redirects]]
from = "/notiz/subversion-1-theorie-und-funktionsweise"
to = "/2007/subversion-1-theorie-und-funktionsweise"
status = 301
force = true

[[redirects]]
from = "/notiz/domains-extern-hosten"
to = "/2007/domains-extern-hosten"
status = 301
force = true

[[redirects]]
from = "/notiz/subversion-2-installation"
to = "/2007/subversion-2-installation"
status = 301
force = true

[[redirects]]
from = "/notiz/j2ee-vs-ruby-python-frameworks"
to = "/2007/j2ee-vs-ruby-python-frameworks"
status = 301
force = true

[[redirects]]
from = "/notiz/subversion-3-einrichten-des-repository"
to = "/2007/subversion-3-einrichten-des-repository"
status = 301
force = true

[[redirects]]
from = "/notiz/subversion-4-importieren-einer-projektstruktur"
to = "/2007/subversion-4-importieren-einer-projektstruktur"
status = 301
force = true

[[redirects]]
from = "/notiz/versionskontrolle-mit-git"
to = "/2007/versionskontrolle-mit-git"
status = 301
force = true

[[redirects]]
from = "/versionskontrolle-mit-git"
to = "/2007/versionskontrolle-mit-git"
status = 301
force = true

[[redirects]]
from = "/notiz/lebensmittel-datenbank"
to = "/2007/lebensmittel-datenbank"
status = 301
force = true

[[redirects]]
from = "/notiz/subversion-5-arbeiten-mit-subversion"
to = "/2007/subversion-5-arbeiten-mit-subversion"
status = 301
force = true

[[redirects]]
from = "/notiz/wunschliste-computerspiele-als-film"
to = "/2007/wunschliste-computerspiele-als-film"
status = 301
force = true

[[redirects]]
from = "/notiz/subversion-6-ein-paar-wichtige-befehle"
to = "/2007/subversion-6-ein-paar-wichtige-befehle"
status = 301
force = true

[[redirects]]
from = "/notiz/provoc-vokabeln-lernen-unter-mac-os-x"
to = "/2007/provoc-vokabeln-lernen-unter-mac-os-x"
status = 301
force = true

[[redirects]]
from = "/notiz/eineinhalb-jahre-gtd-eine-billanz"
to = "/2007/eineinhalb-jahre-gtd-eine-billanz"
status = 301
force = true

[[redirects]]
from = "/notiz/traditionelle-japanische-farben-photoshop-illustrator"
to = "/2007/traditionelle-japanische-farben-photoshop-illustrator"
status = 301
force = true

[[redirects]]
from = "/notiz/gtd-mit-omnifocus-oder-things"
to = "/2007/gtd-mit-omnifocus-oder-things"
status = 301
force = true

[[redirects]]
from = "/notiz/das-war-mein-2007-eine-jahresbilanz"
to = "/2007/das-war-mein-2007-eine-jahresbilanz"
status = 301
force = true

[[redirects]]
from = "/notiz/5-gefaehrliche-dinge-die-jedes-kind-gemacht-haben-sollte"
to = "/2008/5-gefaehrliche-dinge-die-jedes-kind-gemacht-haben-sollte"
status = 301
force = true

[[redirects]]
from = "/notiz/gtd-analog-vs-digital-0-zu-1"
to = "/"
status = 410
force = true

[[redirects]]
from = "/2008/gtd-analog-vs-digital-0-zu-1"
to = "/"
status = 410
force = true

[[redirects]]
from = "/notiz/lokalisierung-von-projekten-mit-django"
to = "/2008/lokalisierung-von-projekten-mit-django"
status = 301
force = true

[[redirects]]
from = "/notiz/weiterleitung-redirect-django"
to = "/2008/weiterleitung-redirect-django"
status = 301
force = true

[[redirects]]
from = "/notiz/server-verwaltung-fabric"
to = "/2008/server-verwaltung-fabric"
status = 301
force = true

[[redirects]]
from = "/notiz/einstieg-in-git-als-versionskontrollsystem"
to = "/2009/einstieg-in-git-als-versionskontrollsystem"
status = 301
force = true

[[redirects]]
from = "/notiz/gitweb-theme-github-stil"
to = "/2009/gitweb-theme-github-stil"
status = 301
force = true

[[redirects]]
from = "/notiz/things-evernote-gtd-mac-osx"
to = "/2009/things-evernote-gtd-mac-osx"
status = 301
force = true

[[redirects]]
from = "/notiz/home-atemberaubende-erde-dokumentation-yann-arthus-bertrand"
to = "/2009/home-atemberaubende-erde-dokumentation-yann-arthus-bertrand"
status = 301
force = true

[[redirects]]
from = "/notiz/git-praesentation"
to = "/2009/git-praesentation"
status = 301
force = true

[[redirects]]
from = "/notiz/buchtipp-rework-37signals"
to = "/2010/buchtipp-rework-37signals"
status = 301
force = true

[[redirects]]
from = "/notiz/appletv-leihfilme-itunes"
to = "/2010/appletv-leihfilme-itunes"
status = 301
force = true

[[redirects]]
from = "/notiz/geloeste-django-probleme"
to = "/2010/geloeste-django-probleme"
status = 301
force = true

[[redirects]]
from = "/notiz/webstandards-magazin-django"
to = "/2010/webstandards-magazin-django"
status = 301
force = true

[[redirects]]
from = "/notiz/auto-complete-im-terminal"
to = "/2010/auto-complete-im-terminal"
status = 301
force = true

[[redirects]]
from = "/notiz/vim"
to = "/2010/vim"
status = 301
force = true

[[redirects]]
from = "/notiz/automatisierung-mit-keyboard-maestro"
to = "/2011/automatisierung-mit-keyboard-maestro"
status = 301
force = true

[[redirects]]
from = "/notiz/buchtipp-decodeunicode"
to = "/2011/buchtipp-decodeunicode"
status = 301
force = true

[[redirects]]
from = "/notiz/duplikation-ist-in-ordnung"
to = "/2013/duplikation-ist-in-ordnung"
status = 301
force = true

[[redirects]]
from = "/notiz/wichtig-website-neu"
to = "/2014/relaunch-responsive-web-design"
status = 301
force = true

[[redirects]]
from = "/notiz/automatisierte-installation-mac-os-x"
to = "/2014/automatisierte-installation-mac-os-x"
status = 301
force = true

[[redirects]]
from = "/main/kategorie/gtd"
to = "/categories/produktivitaet"
status = 301
force = true

[[redirects]]
from = "/main/kategorie/python"
to = "/tag/python"
status = 301
force = true

[[redirects]]
from = "/main/kategorie/django"
to = "/tag/django"
status = 301
force = true

[[redirects]]
from = "/notiz/django"
to = "/tag/django"
status = 301
force = true

[[redirects]]
from = "/2007/domains-extern-hosten/"
to = "/extern-domain-hosting/"
status = 301
force = true

[[redirects]]
from = "/2007/koi-design/"
to = "/koi-design/"
status = 301
force = true

[[redirects]]
from = "/2007/eineinhalb-jahre-gtd-eine-billanz/"
to = "/gtd/"
status = 301
force = true

[[redirects]]
from = "/2007/traditionelle-japanische-farben-photoshop-illustrator/"
to = "/japanese-colors/"
status = 301
force = true

[[redirects]]
from = "/2008/kostenlose-vektorkarten-openstreetmap/"
to = "/openstreetmap/"
status = 301
force = true

[[redirects]]
from = "/2009/einstieg-in-git-als-versionskontrollsystem/"
to = "/git/"
status = 301
force = true

[[redirects]]
from = "/2009/gitweb-theme-github-stil/"
to = "/gitweb-theme/"
status = 301
force = true

[[redirects]]
from = "/2009/home-atemberaubende-erde-dokumentation-yann-arthus-bertrand/"
to = "/home-documentary/"
status = 301
force = true

[[redirects]]
from = "/2010/buchtipp-rework-37signals/"
to = "/rework/"
status = 301
force = true

[[redirects]]
from = "/2010/webstandards-magazin-django/"
to = "/webstandards-magazine-django/"
status = 301
force = true

[[redirects]]
from = "/2010/vim/"
to = "/vim/"
status = 301
force = true

[[redirects]]
from = "/2011/buchtipp-decodeunicode/"
to = "/decodeunicode/"
status = 301
force = true

[[redirects]]
from = "/2014/automatisierte-installation-mac-os-x/"
to = "/brew-automatic-installation/"
status = 301
force = true

[[redirects]]
from = "/2014/gestaltung-neues-logo/"
to = "/logo-design/"
status = 301
force = true

[[redirects]]
from = "/2014/die-typographie-meiner-website/"
to = "/website-typography/"
status = 301
force = true

[[redirects]]
from = "/2014/john-seymour-buecher-selbstversorgung/"
to = "/john-seymour-books/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-1-intro-setup/"
to = "/gulp-tutorial-1-intro-setup/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-2-development-server-browsersync-configuration/"
to = "/gulp-tutorial-2-development-server-browsersync-configuration/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-3-build-clean-jekyll/"
to = "/gulp-tutorial-3-build-clean-jekyll/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-4-css-generation-sass/"
to = "/gulp-tutorial-4-css-generation-sass/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-5-javascripts-browserify/"
to = "/gulp-tutorial-5-javascripts-browserify/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-6-images-vector-fonts/"
to = "/gulp-tutorial-6-images-vector-fonts/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-7-base64/"
to = "/gulp-tutorial-7-base64/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-8-watch/"
to = "/gulp-tutorial-8-watch/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-9-linting-scss-and-javascript/"
to = "/gulp-tutorial-9-linting-scss-and-javascript/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-10-generating-sprites/"
to = "/gulp-tutorial-10-generating-sprites/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-11-production-build-server-and-jekyll/"
to = "/gulp-tutorial-11-production-build-server-and-jekyll/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-12-optimize-css-javascript-images-and-html/"
to = "/gulp-tutorial-12-optimize-css-javascript-images-and-html/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-13-revisioning/"
to = "/gulp-tutorial-13-revisioning/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-14-deploying-the-website/"
to = "/gulp-tutorial-14-deploying-the-website/"
status = 301
force = true

[[redirects]]
from = "/2014/gulp-tutorial-15-performance-improvements-webp-gzip/"
to = "/gulp-tutorial-15-performance-improvements-webp-gzip/"
status = 301
force = true

[[redirects]]
from = "/2015/responsive-relaunch-of-my-martial-arts-website/"
to = "/responsive-relaunch-martial-arts-website/"
status = 301
force = true

[[redirects]]
from = "/2015/getting-started-with-body-weight-training/"
to = "/calisthenics/"
status = 301
force = true

[[redirects]]
from = "/2015/motivational-video/"
to = "/motivational-video/"
status = 301
force = true

[[redirects]]
from = "/2015/human-film-yann-arthus-bertrand/"
to = "/human-documentary/"
status = 301
force = true

[[redirects]]
from = "/2015/gulp-tutorial-16-postcss/"
to = "/gulp-tutorial-16-postcss/"
status = 301
force = true

[[redirects]]
from = "/2016/japanese-netflix-tv-show-atelier-underwear/"
to = "/japanese-netflix-tv-show-underwear/"
status = 301
force = true

[[redirects]]
from = "/2016/hugo-jekyll-migration/"
to = "/jekyll-hugo-migration/"
status = 301
force = true

[[redirects]]
from = "/2016/speed-up-videos/"
to = "/speed-up-videos/"
status = 301
force = true

[[redirects]]
from = "/2017/pursuit-of-minimalism/"
to = "/minimalism/"
status = 301
force = true

[[redirects]]
from = "/2017/minimalism/"
to = "/minimalism/"
status = 301
force = true

[[redirects]]
from = "/2017/i-wrote-a-book-in-gitbook/"
to = "/gitbook/"
status = 301
force = true

[[redirects]]
from = "/2017/migration-hugo-css-grids-service-worker/"
to = "/website-relaunch-css-grid-layout/"
status = 301
force = true

[[redirects]]
from = "/2017/self-defence-age-of-attention/"
to = "/attention/"
status = 301
force = true

[[redirects]]
from = "/information/impressum"
to = "/impressum"
status = 301
force = true

[[redirects]]
from = "/main/kategorie/tutorial"
to = "/tag/tutorial"
status = 301
force = true

[[redirects]]
from = "/main/kategorie/download"
to = "/tag/download"
status = 301
force = true

[[redirects]]
from = "/notizbuch"
to = "/articles"
status = 301
force = true

[[redirects]]
from = "/archiv"
to = "/articles"
status = 301
force = true
